export type SupportedLocale = 'en' | 'ko' | 'ja';
export type LocaleSelection = 'system' | SupportedLocale;

const englishCatalog = {
  appName: 'Tab Organizer',
  navReview: 'Sync',
  navPresets: 'Presets',
  navLocked: 'Locked',
  navSettings: 'Settings',
  behaviorTitle: 'Behavior',
  connectTitle: 'Connect {provider}',
  connectDescription:
    'Use your own {provider} API key to enable AI-assisted tab organization.',
  securityTitle: 'Before you connect',
  securityBody:
    'A browser extension cannot provide server-grade secrecy. Use a dedicated {provider} project key, set a spending limit, and keep revocation available.',
  storageNotice:
    'Your key stays in extension-local storage on this device. It is never saved to Chrome Sync or written to logs.',
  dataNotice:
    'Only tab titles, hostnames, existing group details, and preset context are sent to {provider}. Full URLs and page content are not sent.',
  languageLabel: 'Language',
  languageSystem: 'System default',
  languageEnglish: 'English',
  languageKorean: '한국어',
  languageJapanese: '日本語',
  apiKeyLabel: '{provider} API key',
  apiKeyPlaceholder: 'Paste your API key',
  saveAndTest: 'Save and test',
  testingConnection: 'Testing connection',
  deleteKey: 'Delete key',
  maskedKey: 'Saved key',
  statusMissing: 'Add a key to enable organization.',
  statusValid: 'Connected. Organization is enabled.',
  statusInvalid: 'The key was rejected. Organization remains disabled.',
  statusError: 'Connection failed. Organization remains disabled.',
  loading: 'Loading settings',
  organizationLoading: 'Loading organization data',
  syncNeeded: 'Sync tabs that need it',
  syncActiveTab: 'Sync this tab',
  reviewTitle: 'Review tab changes',
  reviewingTabs: 'Reviewing tabs',
  reviewingNotice: 'This runs in the background. Keep using other tabs and windows, and close this popup if you like: the result waits here.',
  reviewEmpty: 'Run a synchronization to review proposed changes.',
  reviewNoChanges: 'Nothing to propose. Every tab in this run either already sits where it belongs or had no group that fits it.',
  reviewedTabs: 'Tabs looked at',
  unchangedCount: 'Unchanged tabs',
  failedTabCount: 'Tabs that could not be reviewed',
  planFailed: 'The grouping plan failed, so each batch of tabs was named on its own. Groups come out fragmented. Reason',
  skippedGroupsTitle: 'Groups left uncreated',
  skippedNotInPlan: 'not one of the names planned for this window',
  skippedTooFewTabs: 'needs {minimum} tabs, has {count}',
  applySelected: 'Apply selected',
  selectedCount: 'Selected changes',
  splitViewBlocked: 'Split View: keep unchanged and exit Split View in Chrome before refreshing.',
  splitViewConflict: 'Split View conflict',
  proposedTarget: 'Proposed target',
  keepUnchanged: 'Keep unchanged',
  selectAll: 'Select all in {group}',
  deselectAll: 'Deselect all in {group}',
  lockTab: 'Lock',
  lockCurrent: 'Lock this tab',
  lockedExcluded: 'Locked, so this run leaves it alone. Unlock it under Locked to include it again.',
  failedAutomatic: 'Failed automatic organization',
  retry: 'Retry',
  presetsTitle: 'Group presets',
  presetOrderNote: 'Drag a preset, or focus its handle and press the up and down arrows. Groups named by a preset are placed in this order when tabs are sorted.',
  presetReorder: 'Reorder {name}',
  presetReorderHint: 'Drag, or press the up and down arrows',
  presetName: 'Name',
  presetDescription: 'Description',
  presetNameRequired: 'Enter a preset name.',
  presetDescriptionNote: 'Optional. It is the only description the model reads for this preset; a text cue is matched here and never sent.',
  presetCues: 'Text cues, comma separated',
  presetColor: 'Color',
  createPreset: 'Create preset',
  updatePreset: 'Update preset',
  edit: 'Edit',
  deletePreset: 'Delete',
  noPresets: 'No presets yet.',
  lockedTitle: 'Locked tabs',
  changedSinceLock: 'Navigated since lock',
  unchangedSinceLock: 'Unchanged since lock',
  unlock: 'Unlock',
  unlockAnalyze: 'Unlock and analyze',
  selectAllLocked: 'Select all',
  deselectAllLocked: 'Deselect all',
  noLockedTabs: 'No locked tabs.',
  modelLabel: 'Classification model',
  saveModel: 'Save model',
  baseUrlLabel: 'API base URL',
  saveBaseUrl: 'Save base URL',
  groupingLabel: 'Grouping breadth',
  groupingBroad: 'Broad - fewer, larger groups',
  groupingBalanced: 'Balanced',
  groupingFine: 'Fine - more, smaller groups',
  cueMatchReason: 'Matched a preset text cue on this device',
  sendPathLabel: 'Also send the URL path when classifying',
  sendPathNotice: 'The query string and fragment are never sent. Paths can still name a private document.',
  baseUrlDefaultNotice: 'Requests and your key go to the default OpenAI endpoint.',
  baseUrlCustomNotice: 'Requests and your key go to this host instead of OpenAI',
  baseUrlInvalid: 'Enter an https address, or an http address on localhost.',
  baseUrlPermissionDenied: 'Chrome denied access to that host, so the endpoint was not changed.',
  firstPageLabel: 'Organize the first page of new tabs automatically',
  sortIncomplete: 'Chrome refused some of the moves, so the order is only partly sorted. Applying again usually finishes it.',
  sortTabsLabel: 'Sort tabs alphabetically after applying',
  sortTabsNotice: 'Groups are ordered by name, tabs inside them by title, and ungrouped tabs go last. Pinned tabs stay put, and a Split View pair moves as one, at the head of wherever it belongs. The order you had is not recorded, so it cannot be restored.',
  operationSuccess: 'Operation completed.',
  operationError: 'The operation failed. No fallback was used.',
  appliedChanges: 'Applied changes',
  skippedChanges: 'Skipped changes',
  organizationLoadError: 'Organization data could not be loaded.',
  saveAsPreset: 'Save as preset',
  savedAsPreset: 'Saved as preset',
  tabLabel: 'Tab',
  windowLabel: 'Window',
  colorGrey: 'Grey',
  colorBlue: 'Blue',
  colorRed: 'Red',
  colorYellow: 'Yellow',
  colorGreen: 'Green',
  colorPink: 'Pink',
  colorPurple: 'Purple',
  colorCyan: 'Cyan',
  colorOrange: 'Orange',
  openInPanel: 'Open side panel',
  resizeWidth: 'Resize the popup width',
  reviewScopeLabel: 'Reviewed',
  reviewScopeAll: 'every window',
  reviewScopeCurrent: 'this window',
  reviewScopeActive: 'this tab',
  reviewScopeUngrouped: 'the tabs in this window that needed a decision',
  providerLabel: 'AI provider',
  providerOpenAi: 'OpenAI',
  providerAnthropic: 'Anthropic Claude',
  providerGoogle: 'Google Gemini',
  providerKeysLabel: 'Saved keys',
  providerKeyPresent: 'key saved',
  providerKeyAbsent: 'no key',
} as const;

type TranslationKey = keyof typeof englishCatalog;
type TranslationCatalog = Record<TranslationKey, string>;

export const translations: Record<SupportedLocale, TranslationCatalog> = {
  en: englishCatalog,
  ko: {
    appName: 'Tab Organizer',
    navReview: '정리',
    navPresets: '프리셋',
    navLocked: '잠긴 탭',
    navSettings: '설정',
    behaviorTitle: '동작',
    connectTitle: '{provider} 연결',
    connectDescription: '사용자 소유 {provider} API 키로 AI 탭 정리 기능을 활성화합니다.',
    securityTitle: '연결 전 확인',
    securityBody:
      '브라우저 확장은 서버 수준의 비밀 보관을 제공할 수 없습니다. 전용 {provider} 프로젝트 키를 만들고 지출 한도와 폐기 방법을 설정하세요.',
    storageNotice:
      '키는 이 기기의 확장 프로그램 로컬 저장소에만 보관됩니다. Chrome 동기화나 로그에는 저장되지 않습니다.',
    dataNotice:
      '{provider}에는 탭 제목, 호스트 이름, 기존 그룹 정보와 프리셋 문맥만 전송합니다. 전체 URL과 페이지 내용은 전송하지 않습니다.',
    languageLabel: '언어',
    languageSystem: '시스템 기본값',
    languageEnglish: 'English',
    languageKorean: '한국어',
    languageJapanese: '日本語',
    apiKeyLabel: '{provider} API 키',
    apiKeyPlaceholder: 'API 키 붙여넣기',
    saveAndTest: '저장 후 연결 테스트',
    testingConnection: '연결 테스트 중',
    deleteKey: '키 삭제',
    maskedKey: '저장된 키',
    statusMissing: '정리 기능을 활성화하려면 키를 추가하세요.',
    statusValid: '연결되었습니다. 정리 기능이 활성화되었습니다.',
    statusInvalid: '키가 거부되었습니다. 정리 기능은 비활성 상태입니다.',
    statusError: '연결에 실패했습니다. 정리 기능은 비활성 상태입니다.',
    loading: '설정 불러오는 중',
    organizationLoading: '정리 데이터 불러오는 중',
    syncNeeded: '필요한 탭 정리',
    syncActiveTab: '이 탭 정리',
    reviewTitle: '탭 변경 검토',
    reviewingTabs: '탭 검토 중',
    reviewingNotice: '백그라운드에서 실행됩니다. 다른 탭과 창을 계속 사용해도 되고, 이 팝업을 닫아도 결과는 여기 남습니다.',
    reviewEmpty: '동기화를 실행해 변경 제안을 검토하세요.',
    reviewNoChanges: '제안할 변경이 없습니다. 이번 대상 탭은 이미 맞는 자리에 있거나, 들어갈 만한 그룹이 없었습니다.',
    reviewedTabs: '검토한 탭',
    unchangedCount: '변경 없는 탭',
    planFailed: '그룹 계획 단계가 실패해 탭 묶음마다 따로 이름을 정했습니다. 그룹이 잘게 쪼개집니다. 사유',
    skippedGroupsTitle: '만들지 않은 그룹',
    skippedNotInPlan: '이 창에 계획된 이름이 아님',
    skippedTooFewTabs: '탭 {minimum}개 필요, 현재 {count}개',
    failedTabCount: '검토하지 못한 탭',
    applySelected: '선택 항목 적용',
    selectedCount: '선택된 변경',
    splitViewBlocked: '분할 화면은 변경하지 않습니다. Chrome에서 분할 화면을 종료한 뒤 새로 검토하세요.',
    splitViewConflict: '분할 화면 충돌',
    proposedTarget: '제안 대상',
    keepUnchanged: '변경하지 않기',
    selectAll: '{group} 전체 선택',
    deselectAll: '{group} 전체 해제',
    lockTab: '잠금',
    lockCurrent: '이 탭 잠금',
    lockedExcluded: '잠겨 있어 이번 적용에서 제외됩니다. 다시 포함하려면 잠긴 탭에서 잠금을 해제하세요.',
    failedAutomatic: '자동 정리 실패',
    retry: '다시 시도',
    presetsTitle: '그룹 프리셋',
    presetOrderNote: '프리셋을 끌어 옮기거나, 손잡이에 포커스를 두고 위아래 방향키를 누르세요. 탭을 정렬할 때 프리셋이 이름을 정한 그룹은 이 순서로 놓입니다.',
    presetReorder: '{name} 순서 변경',
    presetReorderHint: '끌어서 옮기거나 위아래 방향키를 누르세요',
    presetName: '이름',
    presetDescription: '설명',
    presetNameRequired: '프리셋 이름을 입력하세요.',
    presetDescriptionNote: '선택 사항입니다. 모델이 이 프리셋에 대해 읽는 유일한 설명이며, 텍스트 단서는 이 기기에서 처리되어 전송되지 않습니다.',
    presetCues: '텍스트 단서, 쉼표로 구분',
    presetColor: '색상',
    createPreset: '프리셋 만들기',
    updatePreset: '프리셋 수정',
    edit: '수정',
    deletePreset: '삭제',
    noPresets: '프리셋이 없습니다.',
    lockedTitle: '잠긴 탭',
    changedSinceLock: '잠금 후 이동함',
    unchangedSinceLock: '잠금 후 변경 없음',
    unlock: '잠금 해제',
    unlockAnalyze: '잠금 해제 후 분석',
    selectAllLocked: '전체 선택',
    deselectAllLocked: '전체 해제',
    noLockedTabs: '잠긴 탭이 없습니다.',
    modelLabel: '분류 모델',
    saveModel: '모델 저장',
    baseUrlLabel: 'API 기본 주소',
    saveBaseUrl: '기본 주소 저장',
    groupingLabel: '그룹 묶는 정도',
    groupingBroad: '넓게 - 큰 그룹 소수',
    groupingBalanced: '보통',
    groupingFine: '세밀하게 - 작은 그룹 다수',
    cueMatchReason: '이 기기에서 프리셋 텍스트 단서와 일치',
    sendPathLabel: '분류할 때 URL 경로도 전송',
    sendPathNotice: '쿼리스트링과 프래그먼트는 절대 전송하지 않습니다. 다만 경로에도 비공개 문서 이름이 담길 수 있습니다.',
    baseUrlDefaultNotice: '요청과 키가 기본 OpenAI 엔드포인트로 전송됩니다.',
    baseUrlCustomNotice: '요청과 키가 OpenAI 대신 이 호스트로 전송됩니다',
    baseUrlInvalid: 'https 주소를 입력하세요. http는 localhost에서만 허용됩니다.',
    baseUrlPermissionDenied: 'Chrome이 해당 호스트 접근을 거부해 주소를 변경하지 않았습니다.',
    firstPageLabel: '새 탭의 첫 페이지를 자동 정리',
    sortIncomplete: 'Chrome이 일부 이동을 거부해 순서가 부분만 정렬됐습니다. 다시 적용하면 대체로 마무리됩니다.',
    sortTabsLabel: '적용 후 탭을 알파벳순으로 정렬',
    sortTabsNotice: '그룹은 이름순, 그룹 안의 탭은 제목순으로 놓고 그룹에 없는 탭은 뒤로 보냅니다. 고정된 탭은 그대로 두고, 분할 화면 쌍은 한 덩어리로 자기 구역 맨 앞에 놓입니다. 이전 순서는 기록하지 않으므로 복구할 수 없습니다.',
    operationSuccess: '작업이 완료되었습니다.',
    operationError: '작업에 실패했습니다. 대체 분류는 실행하지 않았습니다.',
    appliedChanges: '적용된 변경',
    skippedChanges: '건너뛴 변경',
    organizationLoadError: '정리 데이터를 불러오지 못했습니다.',
    saveAsPreset: '프리셋으로 저장',
    savedAsPreset: '프리셋으로 저장됨',
    tabLabel: '탭',
    windowLabel: '창',
    colorGrey: '회색',
    colorBlue: '파란색',
    colorRed: '빨간색',
    colorYellow: '노란색',
    colorGreen: '초록색',
    colorPink: '분홍색',
    colorPurple: '보라색',
    colorCyan: '청록색',
    colorOrange: '주황색',
    openInPanel: '패널로 열기',
    resizeWidth: '팝업 너비 조절',
    reviewScopeLabel: '검토 범위',
    reviewScopeAll: '모든 창',
    reviewScopeCurrent: '현재 창',
    reviewScopeActive: '이 탭',
    reviewScopeUngrouped: '이 창에서 판단이 필요한 탭',
    providerLabel: 'AI 프로바이더',
    providerOpenAi: 'OpenAI',
    providerAnthropic: 'Anthropic Claude',
    providerGoogle: 'Google Gemini',
    providerKeysLabel: '저장된 키',
    providerKeyPresent: '키 있음',
    providerKeyAbsent: '키 없음',
  },
  ja: {
    appName: 'Tab Organizer',
    navReview: '同期',
    navPresets: 'プリセット',
    navLocked: 'ロック中',
    navSettings: '設定',
    behaviorTitle: '動作',
    connectTitle: '{provider} に接続',
    connectDescription:
      'ご自身の {provider} API キーで AI によるタブ整理を有効にします。',
    securityTitle: '接続する前に',
    securityBody:
      'ブラウザ拡張機能はサーバーと同等の機密性を提供できません。専用の {provider} プロジェクトキーを作成し、利用上限と失効手段を設定してください。',
    storageNotice:
      'キーはこの端末の拡張機能ローカルストレージにのみ保存されます。Chrome 同期やログには保存されません。',
    dataNotice:
      '{provider} にはタブのタイトル、ホスト名、既存グループ情報、プリセットの文脈のみを送信します。完全な URL とページ内容は送信しません。',
    languageLabel: '言語',
    languageSystem: 'システムのデフォルト',
    languageEnglish: 'English',
    languageKorean: '한국어',
    languageJapanese: '日本語',
    apiKeyLabel: '{provider} API キー',
    apiKeyPlaceholder: 'API キーを貼り付け',
    saveAndTest: '保存して接続をテスト',
    testingConnection: '接続をテスト中',
    deleteKey: 'キーを削除',
    maskedKey: '保存済みのキー',
    statusMissing: '整理を有効にするにはキーを追加してください。',
    statusValid: '接続しました。整理が有効です。',
    statusInvalid: 'キーが拒否されました。整理は無効のままです。',
    statusError: '接続に失敗しました。整理は無効のままです。',
    loading: '設定を読み込み中',
    organizationLoading: '整理データを読み込み中',
    syncNeeded: '必要なタブを同期',
    syncActiveTab: 'このタブを同期',
    reviewTitle: 'タブ変更をレビュー',
    reviewingTabs: 'タブをレビュー中',
    reviewingNotice: 'バックグラウンドで実行されます。他のタブやウィンドウを使い続けても、このポップアップを閉じても、結果はここに残ります。',
    reviewEmpty: '同期を実行して変更案を確認してください。',
    reviewNoChanges: '提案する変更はありません。今回の対象タブはすでに適切な場所にあるか、入れるグループがありませんでした。',
    reviewedTabs: '確認したタブ',
    unchangedCount: '変更なしのタブ',
    planFailed: 'グループ計画が失敗し、タブのまとまりごとに個別に名前を決めました。グループが細かく分かれます。理由',
    skippedGroupsTitle: '作成しなかったグループ',
    skippedNotInPlan: 'このウィンドウの計画名に含まれない',
    skippedTooFewTabs: 'タブ{minimum}個必要、現在{count}個',
    failedTabCount: 'レビューできなかったタブ',
    applySelected: '選択項目を適用',
    selectedCount: '選択した変更',
    splitViewBlocked: '分割表示は変更しません。Chrome で分割表示を終了してから更新してください。',
    splitViewConflict: '分割表示の競合',
    proposedTarget: '提案先',
    keepUnchanged: '変更しない',
    selectAll: '{group} をすべて選択',
    deselectAll: '{group} の選択をすべて解除',
    lockTab: 'ロック',
    lockCurrent: 'このタブをロック',
    lockedExcluded: 'ロック中のため、この適用では対象外です。含めるにはロック済みタブで解除してください。',
    failedAutomatic: '自動整理の失敗',
    retry: '再試行',
    presetsTitle: 'グループプリセット',
    presetOrderNote: 'プリセットをドラッグするか、ハンドルにフォーカスして上下の矢印キーを押します。タブを並べ替えるとき、プリセットが名前を付けたグループはこの順序で配置されます。',
    presetReorder: '{name} の順序を変更',
    presetReorderHint: 'ドラッグするか上下の矢印キーを押してください',
    presetName: '名前',
    presetDescription: '説明',
    presetNameRequired: 'プリセット名を入力してください。',
    presetDescriptionNote: '任意です。モデルがこのプリセットについて読む唯一の説明で、テキストの手がかりはこの端末で処理され送信されません。',
    presetCues: 'テキスト手掛かり、カンマ区切り',
    presetColor: '色',
    createPreset: 'プリセットを作成',
    updatePreset: 'プリセットを更新',
    edit: '編集',
    deletePreset: '削除',
    noPresets: 'プリセットはありません。',
    lockedTitle: 'ロック中のタブ',
    changedSinceLock: 'ロック後に移動',
    unchangedSinceLock: 'ロック後の変更なし',
    unlock: 'ロック解除',
    unlockAnalyze: 'ロック解除して分析',
    selectAllLocked: 'すべて選択',
    deselectAllLocked: 'すべて解除',
    noLockedTabs: 'ロック中のタブはありません。',
    modelLabel: '分類モデル',
    saveModel: 'モデルを保存',
    baseUrlLabel: 'API ベース URL',
    saveBaseUrl: 'ベース URL を保存',
    groupingLabel: 'グループのまとめ方',
    groupingBroad: '広く - 大きいグループを少数',
    groupingBalanced: '標準',
    groupingFine: '細かく - 小さいグループを多数',
    cueMatchReason: 'この端末でプリセットのテキスト手がかりと一致',
    sendPathLabel: '分類時に URL パスも送信',
    sendPathNotice: 'クエリ文字列とフラグメントは送信しません。ただしパスにも非公開文書の名前が含まれることがあります。',
    baseUrlDefaultNotice: 'リクエストとキーは既定の OpenAI エンドポイントに送信されます。',
    baseUrlCustomNotice: 'リクエストとキーは OpenAI ではなくこのホストに送信されます',
    baseUrlInvalid: 'https のアドレスを入力してください。http は localhost のみ使用できます。',
    baseUrlPermissionDenied: 'Chrome がそのホストへのアクセスを拒否したため、アドレスは変更されていません。',
    firstPageLabel: '新しいタブの最初のページを自動整理',
    sortIncomplete: 'Chrome が一部の移動を拒否したため、順序は部分的にしか整っていません。もう一度適用すればたいてい完了します。',
    sortTabsLabel: '適用後にタブをアルファベット順に並べ替える',
    sortTabsNotice: 'グループは名前順、グループ内のタブはタイトル順に並べ、グループに属さないタブは後ろに送ります。固定されたタブはそのままで、分割画面のペアは一つの塊として区画の先頭に置かれます。以前の順序は記録しないため、復元できません。',
    operationSuccess: '操作が完了しました。',
    operationError: '操作に失敗しました。代替分類は実行されていません。',
    appliedChanges: '適用した変更',
    skippedChanges: 'スキップした変更',
    organizationLoadError: '整理データを読み込めませんでした。',
    saveAsPreset: 'プリセットとして保存',
    savedAsPreset: 'プリセットに保存済み',
    tabLabel: 'タブ',
    windowLabel: 'ウィンドウ',
    colorGrey: 'グレー',
    colorBlue: '青',
    colorRed: '赤',
    colorYellow: '黄',
    colorGreen: '緑',
    colorPink: 'ピンク',
    colorPurple: '紫',
    colorCyan: 'シアン',
    colorOrange: 'オレンジ',
    openInPanel: 'サイドパネルで開く',
    resizeWidth: 'ポップアップの幅を変更',
    reviewScopeLabel: 'レビュー範囲',
    reviewScopeAll: 'すべてのウィンドウ',
    reviewScopeCurrent: 'このウィンドウ',
    reviewScopeActive: 'このタブ',
    reviewScopeUngrouped: 'このウィンドウで判断が必要なタブ',
    providerLabel: 'AI プロバイダ',
    providerOpenAi: 'OpenAI',
    providerAnthropic: 'Anthropic Claude',
    providerGoogle: 'Google Gemini',
    providerKeysLabel: '保存済みキー',
    providerKeyPresent: 'キーあり',
    providerKeyAbsent: 'キーなし',
  },
};

/**
 * Fills the provider placeholder in a catalog string.
 *
 * These sentences name the service the key belongs to and the service tab titles are sent to, so a
 * fixed name would be wrong for two of the three providers.
 */
export function withProviderName(template: string, providerName: string): string {
  return fillPlaceholders(template, { provider: providerName });
}

/** Replaces every `{name}` in a catalog string, so word order stays with the translation. */
export function fillPlaceholders(
  template: string,
  values: Record<string, string | number>,
): string {
  return Object.entries(values).reduce(
    (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
    template,
  );
}

export type { TranslationKey };

export function resolveLocale(
  selection: LocaleSelection,
  systemLocale: string,
): SupportedLocale {
  if (selection !== 'system') {
    return selection;
  }

  const primaryLanguage = systemLocale.toLowerCase().split('-')[0];
  if (primaryLanguage === 'ko' || primaryLanguage === 'ja') {
    return primaryLanguage;
  }

  return 'en';
}
