export type SupportedLocale = 'en' | 'ko' | 'ja';
export type LocaleSelection = 'system' | SupportedLocale;

const englishCatalog = {
  appName: 'Tab Organizer',
  navReview: 'Review',
  navPresets: 'Presets',
  navLocked: 'Locked',
  navHistory: 'History',
  navSettings: 'Settings',
  behaviorTitle: 'Behavior',
  connectTitle: 'Connect {provider}',
  connectDescription:
    'Use your own {provider} API key to enable AI-assisted tab organization.',
  securityTitle: 'Before you connect',
  securityBody:
    'A browser extension cannot provide server-grade secrecy. Use a dedicated {provider} project key, set a spending limit, and keep revocation available.',
  storageNotice:
    'Your key stays in extension-local storage on this device. It is never saved to Chrome Sync or written to logs.',
  dataNotice:
    'Only tab titles, hostnames, existing group details, and preset context are sent to {provider}. Full URLs and page content are not sent.',
  languageLabel: 'Language',
  languageSystem: 'System default',
  languageEnglish: 'English',
  languageKorean: '한국어',
  languageJapanese: '日本語',
  apiKeyLabel: '{provider} API key',
  apiKeyPlaceholder: 'Paste your API key',
  saveAndTest: 'Save and test',
  testingConnection: 'Testing connection',
  deleteKey: 'Delete key',
  maskedKey: 'Saved key',
  statusMissing: 'Add a key to enable organization.',
  statusValid: 'Connected. Organization is enabled.',
  statusInvalid: 'The key was rejected. Organization remains disabled.',
  statusError: 'Connection failed. Organization remains disabled.',
  loading: 'Loading settings',
  organizationLoading: 'Loading organization data',
  syncAll: 'Sync all windows',
  syncCurrent: 'Sync current window',
  reviewTitle: 'Review tab changes',
  reviewingTabs: 'Reviewing tabs',
  reviewEmpty: 'Run a synchronization to review proposed changes.',
  unchangedCount: 'Unchanged tabs',
  failedTabCount: 'Tabs that could not be reviewed',
  applySelected: 'Apply selected',
  selectedCount: 'Selected changes',
  splitViewBlocked: 'Split View: keep unchanged and exit Split View in Chrome before refreshing.',
  splitViewConflict: 'Split View conflict',
  proposedTarget: 'Proposed target',
  keepUnchanged: 'Keep unchanged',
  rejectGroup: 'Reject group',
  lockTab: 'Lock',
  lockCurrent: 'Lock current tab',
  failedAutomatic: 'Failed automatic organization',
  retry: 'Retry',
  presetsTitle: 'Group presets',
  presetName: 'Name',
  presetDescription: 'Description',
  presetNameRequired: 'Enter a preset name.',
  presetDescriptionRequired: 'Enter a preset description.',
  presetCues: 'Text cues, comma separated',
  presetColor: 'Color',
  createPreset: 'Create preset',
  updatePreset: 'Update preset',
  edit: 'Edit',
  deletePreset: 'Delete',
  noPresets: 'No presets yet.',
  lockedTitle: 'Locked tabs',
  changedSinceLock: 'Navigated since lock',
  unchangedSinceLock: 'Unchanged since lock',
  unlock: 'Unlock',
  unlockAnalyze: 'Unlock and analyze',
  noLockedTabs: 'No locked tabs.',
  historyTitle: 'Organization history',
  undo: 'Undo',
  undone: 'Undone',
  noHistory: 'No organization history.',
  modelLabel: 'Classification model',
  saveModel: 'Save model',
  baseUrlLabel: 'API base URL',
  saveBaseUrl: 'Save base URL',
  groupingLabel: 'Grouping breadth',
  groupingBroad: 'Broad - fewer, larger groups',
  groupingBalanced: 'Balanced',
  groupingFine: 'Fine - more, smaller groups',
  cueMatchReason: 'Matched a preset text cue on this device',
  sendPathLabel: 'Also send the URL path when classifying',
  sendPathNotice: 'The query string and fragment are never sent. Paths can still name a private document.',
  baseUrlDefaultNotice: 'Requests and your key go to the default OpenAI endpoint.',
  baseUrlCustomNotice: 'Requests and your key go to this host instead of OpenAI',
  baseUrlInvalid: 'Enter an https address, or an http address on localhost.',
  baseUrlPermissionDenied: 'Chrome denied access to that host, so the endpoint was not changed.',
  firstPageLabel: 'Organize the first page of new tabs automatically',
  operationSuccess: 'Operation completed.',
  operationError: 'The operation failed. No fallback was used.',
  appliedChanges: 'Applied changes',
  skippedChanges: 'Skipped changes',
  organizationLoadError: 'Organization data could not be loaded.',
  saveAsPreset: 'Save as preset',
  tabLabel: 'Tab',
  operationAutomatic: 'Automatic',
  operationSync: 'Synchronization',
  windowLabel: 'Window',
  colorGrey: 'Grey',
  colorBlue: 'Blue',
  colorRed: 'Red',
  colorYellow: 'Yellow',
  colorGreen: 'Green',
  colorPink: 'Pink',
  colorPurple: 'Purple',
  colorCyan: 'Cyan',
  colorOrange: 'Orange',
  openInPanel: 'Open side panel',
  resizeWidth: 'Resize the popup width',
  providerLabel: 'AI provider',
  providerOpenAi: 'OpenAI',
  providerAnthropic: 'Anthropic Claude',
  providerGoogle: 'Google Gemini',
  providerKeysLabel: 'Saved keys',
  providerKeyPresent: 'key saved',
  providerKeyAbsent: 'no key',
} as const;

type TranslationKey = keyof typeof englishCatalog;
type TranslationCatalog = Record<TranslationKey, string>;

export const translations: Record<SupportedLocale, TranslationCatalog> = {
  en: englishCatalog,
  ko: {
    appName: 'Tab Organizer',
    navReview: '검토',
    navPresets: '프리셋',
    navLocked: '잠긴 탭',
    navHistory: '기록',
    navSettings: '설정',
    behaviorTitle: '동작',
    connectTitle: '{provider} 연결',
    connectDescription: '사용자 소유 {provider} API 키로 AI 탭 정리 기능을 활성화합니다.',
    securityTitle: '연결 전 확인',
    securityBody:
      '브라우저 확장은 서버 수준의 비밀 보관을 제공할 수 없습니다. 전용 {provider} 프로젝트 키를 만들고 지출 한도와 폐기 방법을 설정하세요.',
    storageNotice:
      '키는 이 기기의 확장 프로그램 로컬 저장소에만 보관됩니다. Chrome 동기화나 로그에는 저장되지 않습니다.',
    dataNotice:
      '{provider}에는 탭 제목, 호스트 이름, 기존 그룹 정보와 프리셋 문맥만 전송합니다. 전체 URL과 페이지 내용은 전송하지 않습니다.',
    languageLabel: '언어',
    languageSystem: '시스템 기본값',
    languageEnglish: 'English',
    languageKorean: '한국어',
    languageJapanese: '日本語',
    apiKeyLabel: '{provider} API 키',
    apiKeyPlaceholder: 'API 키 붙여넣기',
    saveAndTest: '저장 후 연결 테스트',
    testingConnection: '연결 테스트 중',
    deleteKey: '키 삭제',
    maskedKey: '저장된 키',
    statusMissing: '정리 기능을 활성화하려면 키를 추가하세요.',
    statusValid: '연결되었습니다. 정리 기능이 활성화되었습니다.',
    statusInvalid: '키가 거부되었습니다. 정리 기능은 비활성 상태입니다.',
    statusError: '연결에 실패했습니다. 정리 기능은 비활성 상태입니다.',
    loading: '설정 불러오는 중',
    organizationLoading: '정리 데이터 불러오는 중',
    syncAll: '모든 창 동기화',
    syncCurrent: '현재 창 동기화',
    reviewTitle: '탭 변경 검토',
    reviewingTabs: '탭 검토 중',
    reviewEmpty: '동기화를 실행해 변경 제안을 검토하세요.',
    unchangedCount: '변경 없는 탭',
    failedTabCount: '검토하지 못한 탭',
    applySelected: '선택 항목 적용',
    selectedCount: '선택된 변경',
    splitViewBlocked: '분할 화면은 변경하지 않습니다. Chrome에서 분할 화면을 종료한 뒤 새로 검토하세요.',
    splitViewConflict: '분할 화면 충돌',
    proposedTarget: '제안 대상',
    keepUnchanged: '변경하지 않기',
    rejectGroup: '그룹 거절',
    lockTab: '잠금',
    lockCurrent: '현재 탭 잠금',
    failedAutomatic: '자동 정리 실패',
    retry: '다시 시도',
    presetsTitle: '그룹 프리셋',
    presetName: '이름',
    presetDescription: '설명',
    presetNameRequired: '프리셋 이름을 입력하세요.',
    presetDescriptionRequired: '프리셋 설명을 입력하세요.',
    presetCues: '텍스트 단서, 쉼표로 구분',
    presetColor: '색상',
    createPreset: '프리셋 만들기',
    updatePreset: '프리셋 수정',
    edit: '수정',
    deletePreset: '삭제',
    noPresets: '프리셋이 없습니다.',
    lockedTitle: '잠긴 탭',
    changedSinceLock: '잠금 후 이동함',
    unchangedSinceLock: '잠금 후 변경 없음',
    unlock: '잠금 해제',
    unlockAnalyze: '잠금 해제 후 분석',
    noLockedTabs: '잠긴 탭이 없습니다.',
    historyTitle: '정리 기록',
    undo: '실행 취소',
    undone: '취소됨',
    noHistory: '정리 기록이 없습니다.',
    modelLabel: '분류 모델',
    saveModel: '모델 저장',
    baseUrlLabel: 'API 기본 주소',
    saveBaseUrl: '기본 주소 저장',
    groupingLabel: '그룹 묶는 정도',
    groupingBroad: '넓게 - 큰 그룹 소수',
    groupingBalanced: '보통',
    groupingFine: '세밀하게 - 작은 그룹 다수',
    cueMatchReason: '이 기기에서 프리셋 텍스트 단서와 일치',
    sendPathLabel: '분류할 때 URL 경로도 전송',
    sendPathNotice: '쿼리스트링과 프래그먼트는 절대 전송하지 않습니다. 다만 경로에도 비공개 문서 이름이 담길 수 있습니다.',
    baseUrlDefaultNotice: '요청과 키가 기본 OpenAI 엔드포인트로 전송됩니다.',
    baseUrlCustomNotice: '요청과 키가 OpenAI 대신 이 호스트로 전송됩니다',
    baseUrlInvalid: 'https 주소를 입력하세요. http는 localhost에서만 허용됩니다.',
    baseUrlPermissionDenied: 'Chrome이 해당 호스트 접근을 거부해 주소를 변경하지 않았습니다.',
    firstPageLabel: '새 탭의 첫 페이지를 자동 정리',
    operationSuccess: '작업이 완료되었습니다.',
    operationError: '작업에 실패했습니다. 대체 분류는 실행하지 않았습니다.',
    appliedChanges: '적용된 변경',
    skippedChanges: '건너뛴 변경',
    organizationLoadError: '정리 데이터를 불러오지 못했습니다.',
    saveAsPreset: '프리셋으로 저장',
    tabLabel: '탭',
    operationAutomatic: '자동 정리',
    operationSync: '동기화',
    windowLabel: '창',
    colorGrey: '회색',
    colorBlue: '파란색',
    colorRed: '빨간색',
    colorYellow: '노란색',
    colorGreen: '초록색',
    colorPink: '분홍색',
    colorPurple: '보라색',
    colorCyan: '청록색',
    colorOrange: '주황색',
    openInPanel: '패널로 열기',
    resizeWidth: '팝업 너비 조절',
    providerLabel: 'AI 프로바이더',
    providerOpenAi: 'OpenAI',
    providerAnthropic: 'Anthropic Claude',
    providerGoogle: 'Google Gemini',
    providerKeysLabel: '저장된 키',
    providerKeyPresent: '키 있음',
    providerKeyAbsent: '키 없음',
  },
  ja: {
    appName: 'Tab Organizer',
    navReview: 'レビュー',
    navPresets: 'プリセット',
    navLocked: 'ロック中',
    navHistory: '履歴',
    navSettings: '設定',
    behaviorTitle: '動作',
    connectTitle: '{provider} に接続',
    connectDescription:
      'ご自身の {provider} API キーで AI によるタブ整理を有効にします。',
    securityTitle: '接続する前に',
    securityBody:
      'ブラウザ拡張機能はサーバーと同等の機密性を提供できません。専用の {provider} プロジェクトキーを作成し、利用上限と失効手段を設定してください。',
    storageNotice:
      'キーはこの端末の拡張機能ローカルストレージにのみ保存されます。Chrome 同期やログには保存されません。',
    dataNotice:
      '{provider} にはタブのタイトル、ホスト名、既存グループ情報、プリセットの文脈のみを送信します。完全な URL とページ内容は送信しません。',
    languageLabel: '言語',
    languageSystem: 'システムのデフォルト',
    languageEnglish: 'English',
    languageKorean: '한국어',
    languageJapanese: '日本語',
    apiKeyLabel: '{provider} API キー',
    apiKeyPlaceholder: 'API キーを貼り付け',
    saveAndTest: '保存して接続をテスト',
    testingConnection: '接続をテスト中',
    deleteKey: 'キーを削除',
    maskedKey: '保存済みのキー',
    statusMissing: '整理を有効にするにはキーを追加してください。',
    statusValid: '接続しました。整理が有効です。',
    statusInvalid: 'キーが拒否されました。整理は無効のままです。',
    statusError: '接続に失敗しました。整理は無効のままです。',
    loading: '設定を読み込み中',
    organizationLoading: '整理データを読み込み中',
    syncAll: 'すべてのウィンドウを同期',
    syncCurrent: '現在のウィンドウを同期',
    reviewTitle: 'タブ変更をレビュー',
    reviewingTabs: 'タブをレビュー中',
    reviewEmpty: '同期を実行して変更案を確認してください。',
    unchangedCount: '変更なしのタブ',
    failedTabCount: 'レビューできなかったタブ',
    applySelected: '選択項目を適用',
    selectedCount: '選択した変更',
    splitViewBlocked: '分割表示は変更しません。Chrome で分割表示を終了してから更新してください。',
    splitViewConflict: '分割表示の競合',
    proposedTarget: '提案先',
    keepUnchanged: '変更しない',
    rejectGroup: 'グループを却下',
    lockTab: 'ロック',
    lockCurrent: '現在のタブをロック',
    failedAutomatic: '自動整理の失敗',
    retry: '再試行',
    presetsTitle: 'グループプリセット',
    presetName: '名前',
    presetDescription: '説明',
    presetNameRequired: 'プリセット名を入力してください。',
    presetDescriptionRequired: 'プリセットの説明を入力してください。',
    presetCues: 'テキスト手掛かり、カンマ区切り',
    presetColor: '色',
    createPreset: 'プリセットを作成',
    updatePreset: 'プリセットを更新',
    edit: '編集',
    deletePreset: '削除',
    noPresets: 'プリセットはありません。',
    lockedTitle: 'ロック中のタブ',
    changedSinceLock: 'ロック後に移動',
    unchangedSinceLock: 'ロック後の変更なし',
    unlock: 'ロック解除',
    unlockAnalyze: 'ロック解除して分析',
    noLockedTabs: 'ロック中のタブはありません。',
    historyTitle: '整理履歴',
    undo: '元に戻す',
    undone: '取り消し済み',
    noHistory: '整理履歴はありません。',
    modelLabel: '分類モデル',
    saveModel: 'モデルを保存',
    baseUrlLabel: 'API ベース URL',
    saveBaseUrl: 'ベース URL を保存',
    groupingLabel: 'グループのまとめ方',
    groupingBroad: '広く - 大きいグループを少数',
    groupingBalanced: '標準',
    groupingFine: '細かく - 小さいグループを多数',
    cueMatchReason: 'この端末でプリセットのテキスト手がかりと一致',
    sendPathLabel: '分類時に URL パスも送信',
    sendPathNotice: 'クエリ文字列とフラグメントは送信しません。ただしパスにも非公開文書の名前が含まれることがあります。',
    baseUrlDefaultNotice: 'リクエストとキーは既定の OpenAI エンドポイントに送信されます。',
    baseUrlCustomNotice: 'リクエストとキーは OpenAI ではなくこのホストに送信されます',
    baseUrlInvalid: 'https のアドレスを入力してください。http は localhost のみ使用できます。',
    baseUrlPermissionDenied: 'Chrome がそのホストへのアクセスを拒否したため、アドレスは変更されていません。',
    firstPageLabel: '新しいタブの最初のページを自動整理',
    operationSuccess: '操作が完了しました。',
    operationError: '操作に失敗しました。代替分類は実行されていません。',
    appliedChanges: '適用した変更',
    skippedChanges: 'スキップした変更',
    organizationLoadError: '整理データを読み込めませんでした。',
    saveAsPreset: 'プリセットとして保存',
    tabLabel: 'タブ',
    operationAutomatic: '自動整理',
    operationSync: '同期',
    windowLabel: 'ウィンドウ',
    colorGrey: 'グレー',
    colorBlue: '青',
    colorRed: '赤',
    colorYellow: '黄',
    colorGreen: '緑',
    colorPink: 'ピンク',
    colorPurple: '紫',
    colorCyan: 'シアン',
    colorOrange: 'オレンジ',
    openInPanel: 'サイドパネルで開く',
    resizeWidth: 'ポップアップの幅を変更',
    providerLabel: 'AI プロバイダ',
    providerOpenAi: 'OpenAI',
    providerAnthropic: 'Anthropic Claude',
    providerGoogle: 'Google Gemini',
    providerKeysLabel: '保存済みキー',
    providerKeyPresent: 'キーあり',
    providerKeyAbsent: 'キーなし',
  },
};

/**
 * Fills the provider placeholder in a catalog string.
 *
 * These sentences name the service the key belongs to and the service tab titles are sent to, so a
 * fixed name would be wrong for two of the three providers.
 */
export function withProviderName(template: string, providerName: string): string {
  return template.replaceAll('{provider}', providerName);
}

export type { TranslationKey };

export function resolveLocale(
  selection: LocaleSelection,
  systemLocale: string,
): SupportedLocale {
  if (selection !== 'system') {
    return selection;
  }

  const primaryLanguage = systemLocale.toLowerCase().split('-')[0];
  if (primaryLanguage === 'ko' || primaryLanguage === 'ja') {
    return primaryLanguage;
  }

  return 'en';
}
